title: Filippo Carraro
logo: /assets/img/filippo-profile-picture-small.png

description: Data Analyst
# show_downloads: true
theme: jekyll-theme-minimal
### Skills
- SQL
- Python
- Excel, Google Sheets
- Tableau, Looker
- Team leadership
- Supplier management
- Project management
